# Generated by Django 5.2.3 on 2025-06-19 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.FloatField(blank=True, null=True)),
                ('check_in_lng', models.FloatField(blank=True, null=True)),
                ('check_out_lat', models.FloatField(blank=True, null=True)),
                ('check_out_lng', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_worked_hours', models.DurationField()),
                ('late_minutes', models.IntegerField(default=0)),
                ('was_late', models.BooleanField(default=False)),
                ('was_absent', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_out', models.BooleanField(default=False)),
            ],
        ),
    ]
