# Generated by Django 5.2.3 on 2025-06-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='is_read',
        ),
    ]
